# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ModMeta Relay CI Build

on:
  push:
    branches: [ master, develop ]
    paths-ignore:
      - "docs/**"
      - ".github/workflows/docs.yml"
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ develop ]
    paths-ignore:
      - "docs/**"
      - ".github/workflows/docs.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Run the Cake script
      uses: cake-build/cake-action@v1
      with:
        target: Release
        cake-bootstrap: true
      env:
        QUAY_TOKEN: ${{secrets.QUAY_TOKEN}}
        QUAY_USER: modmeta-relay+github
        NUGET_TOKEN: ${{secrets.NUGET_TOKEN}}
    - uses: actions/upload-artifact@v1
      name: Upload Relay Server
      with:
        name: modmeta-relay
        path: dist/publish/
    - uses: actions/upload-artifact@v1
      if: startsWith(github.ref, 'refs/tags/')
      name: Upload Plugins
      with:
        name: modmeta-plugins
        path: dist/plugins/
    - uses: actions/upload-artifact@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: build_archives
        path: dist/archive/
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v1
      with:
        name: build_archives
        path: assets/
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with: 
        files: |
          ./assets/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}